name: CI

on:
  workflow_call:
  push:
  pull_request:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: |
          pip install --upgrade pip pipenv
          pipenv install --dev --system
      - name: Run unit tests
        run: pytest test -s
      - name: Linting (flake8)
        run: flake8
#      - name: Linting (pylint)
#        run: pylint
      - name: Unit tests (pytest)
        run: pytest test -s

  docker:
    needs: unit-tests
    name: Docker
    uses: ./.github/workflows/docker.yml
    permissions:
      packages: write
